[build]
publish = "public"
command = "vite build"

[dev]
command = "vite"
targetPort = 5173
port = 8888
publish = "public"

[functions]
timeout = 26

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
