[build]
  publish = "public"
  command = "# no build command"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "public"
  framework = "#custom"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/stt"
  to = "/.netlify/functions/stt"
  status = 200

[[redirects]]
  from = "/ai"
  to = "/.netlify/functions/ai"
  status = 200

[[redirects]]
  from = "/tts"
  to = "/.netlify/functions/tts"
  status = 200