[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["axios", "form-data"]

[functions.stt]
  timeout = 26

[functions.ai]
  timeout = 26

[functions.tts]
  timeout = 26

[[redirects]]
  from = "/stt"
  to = "/.netlify/functions/stt"
  status = 200
  force = true

[[redirects]]
  from = "/ai"
  to = "/.netlify/functions/ai"
  status = 200
  force = true

[[redirects]]
  from = "/tts"
  to = "/.netlify/functions/tts"
  status = 200
  force = true